apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: 2017-07-06T15:33:04Z
    labels:
      run: eventhandler-queue
    name: eventhandler-queue
    namespace: default
    resourceVersion: "17538"
    selfLink: /api/v1/namespaces/default/services/eventhandler-queue
    uid: 66f4b757-6260-11e7-aa40-080027123dad
  spec:
    ports:
    - port: 4222
      protocol: TCP
      targetPort: 4222
    selector:
      run: eventhandler-queue
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: 2017-07-06T15:31:17Z
    generation: 1
    labels:
      run: eventhandler-queue
    name: eventhandler-queue
    namespace: default
    resourceVersion: "17420"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/eventhandler-queue
    uid: 2735bee6-6260-11e7-aa40-080027123dad
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: eventhandler-queue
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: eventhandler-queue
      spec:
        containers:
        - image: eventhandler/queue
          imagePullPolicy: IfNotPresent
          name: eventhandler-queue
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          args: ["--debug"]
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2017-07-06T15:39:42Z
      lastUpdateTime: 2017-07-06T15:39:42Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: 2017-07-06T15:39:50Z
    generation: 1
    labels:
      run: subscriber-west
    name: subscriber-west
    namespace: default
    resourceVersion: "18232"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/eventhandler-subscriber
    uid: 5914a31a-6261-11e7-aa40-080027123dad
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: subscriber-west
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: subscriber-west
      spec:
        containers:
        - image: eventhandler/subscriber
          imagePullPolicy: IfNotPresent
          name: subscriber-west
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2017-07-06T15:39:50Z
      lastUpdateTime: 2017-07-06T15:39:50Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
    creationTimestamp: 2017-07-06T15:39:50Z
    generation: 1
    labels:
      run: subscriber-east
    name: subscriber-east
    namespace: default
    resourceVersion: "18232"
    selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/eventhandler-subscriber
    uid: 5914a31a-6261-11e7-aa40-080027123dad
  spec:
    replicas: 1
    selector:
      matchLabels:
        run: subscriber-east
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
    template:
      metadata:
        creationTimestamp: null
        labels:
          run: subscriber-east
      spec:
        containers:
        - image: eventhandler/subscriber
          imagePullPolicy: IfNotPresent
          name: subscriber-east
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
kind: List
metadata: {}
resourceVersion: ""
selfLink: ""
