---
sender: "nagios.example.com"
# passed in as env var
# recipient: "me.example.com"
signkey: "verify/testdata/private.key"
nats_url: "nats://eventhandler-queue:4222"
subject: "eventhandler"

command:
  cmd: "/bin/cat"
  cmdargs:
    - "-"
  timeout: "2s"
  stdintemplate: '{{ . | printf "%v" }}'
  blackout: 5s
  maxdispatches: 3

filters:
  - type: regexp
    context: payload map
    args:
      field: "check_name"
      regexp: "check_.+"
  - type: regexp
    context: envelope
    args:
      field: "sender"
      regexp: "nagios.example.com"
  - type: regexp
    context: envelope
    args:
      field: "recipient"
      regexp: "subscriber"
  - type: signature
    context: signature
    args:
      verifykey: "verify/testdata/public.key"
